### ISSUE TITLE
Register Files for SE2021

### ISSUE THREAD

**Issue by Niklas123Niklas** [uk-dave/SolidEdge#1]
Hi UK-Dave

does reset_solid_edge_extensions_SE2020.reg work with 2021? If not, can you provide a verison for 2021?

Cheers
Niklas

**Comment by uk-dave** [comment]
Niklas,

There is typically a difference between the Solid Edge versions.  I currently do not have a SE2021 version created but please give me some time and I will get this posted.

Thank you and regards,

-Dave

**Comment by uk-dave** [comment]
2021 version of file now uploaded.

Thank you and regards,

-Dave
